version: 1
disable_existing_loggers: False
formatters:
    simple:
        # See https://docs.python.org/3/library/logging.html#logrecord-attributes
        # for the full list of available formatting placeholders
        format: "%(asctime)s %(levelname)-8s [%(filename)s:%(lineno)d - %(funcName)s]: %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
loggers:
    # Package level loggers
    src:
        # __LOGLEVEL__ will be substituted with the value of LOGLEVEL from settings.ini
        level: INFO
        handlers:
            - console
        propagate: no
# Root logger
root:
    level: INFO
    handlers:
        - console


